#!/usr/bin/env bash
# docs/02-plan-your-content.md -- "Compose your configuration"
# Run on: CONNECTED bastion
#
#   ./scripts/12-compose-imageset.sh virtualization compliance-stig storage-lvms
#
# Assembles base-platform.yaml plus the named profiles into a single
# ImageSetConfiguration at ${IMAGESET_CONFIG}.
#
# Fragments are plain text delimited by "# >>> <section>" / "# <<< <section>"
# markers. This script collects the header, platform, operators and
# additionalImages sections from each fragment, concatenates them in order,
# and emits the surrounding YAML structure. Multiple profiles contributing
# operators to the same catalog are merged under one catalog entry.
#
# No YAML library is required -- registry hosts often lack PyYAML.

source "$(dirname "$0")/lib/common.sh"
load_env
require_vars OCP_CHANNEL OCP_VERSION OCP_ARCH IMAGESET_CONFIG
require_cmds python3

PROFILE_DIR="${REPO_ROOT}/imageset-configs/profiles"
BASE="${REPO_ROOT}/imageset-configs/base-platform.yaml"

# Derive the catalog minor version (4.21.34 -> 4.21) used by profile fragments.
OCP_MINOR="${OCP_VERSION%.*}"
export OCP_MINOR

if (( $# == 0 )); then
  cat >&2 <<EOF
Usage: $0 <profile> [profile...]

base-platform.yaml is always included. Available profiles:

EOF
  for f in "${PROFILE_DIR}"/*.yaml; do
    name=$(basename "${f}" .yaml)
    desc=$(sed -n 's/^# Summary: *//p' "${f}" | head -1)
    printf '  %-18s %s\n' "${name}" "${desc}" >&2
  done
  cat >&2 <<EOF

Example:
  $0 virtualization storage-lvms compliance-stig

Each profile carries notes about what it obliges the install side to do.
Read them -- several describe behaviour that is not discoverable later.
EOF
  exit 1
fi

for p in "$@"; do
  [[ -f "${PROFILE_DIR}/${p}.yaml" ]] || die "No such profile: ${p} (run with no arguments to list)"
done

run mkdir -p "$(dirname "${IMAGESET_CONFIG}")"
info "Composing: base-platform $*"

# load_env deliberately does NOT export (see scripts/lib/common.sh -- the
# REGISTRY_* namespace collides with oc-mirror's embedded registry), so the
# python block below cannot see these through os.environ unless we export
# them here explicitly. OCP_* is safe to export.
export OCP_CHANNEL OCP_VERSION OCP_ARCH OCP_MINOR

files=("${BASE}")
for p in "$@"; do files+=("${PROFILE_DIR}/${p}.yaml"); done

python3 - "${IMAGESET_CONFIG}" "$*" "${files[@]}" <<'PY'
import os, re, sys, datetime

out_path, profile_list = sys.argv[1], sys.argv[2]
files = sys.argv[3:]

def sections(path):
    """Return {section_name: [lines]} for >>> / <<< delimited blocks."""
    found, cur, buf = {}, None, []
    for line in open(path):
        m = re.match(r'^#\s*>>>\s*(\S+)', line)
        if m:
            cur, buf = m.group(1), []
            continue
        m = re.match(r'^#\s*<<<\s*(\S+)', line)
        if m:
            if cur:
                found.setdefault(cur, []).extend(buf)
            cur = None
            continue
        if cur is not None:
            buf.append(line.rstrip('\n'))
    return found

header, platform, operators, images = [], [], [], []
for f in files:
    s = sections(f)
    header.extend(s.get('header', []))
    platform.extend(s.get('platform', []))
    ops = s.get('operators', [])
    if ops:
        operators.append((os.path.basename(f)[:-5], ops))
    imgs = s.get('additionalImages', [])
    if imgs:
        images.append((os.path.basename(f)[:-5], imgs))

# Merge operator blocks that target the same catalog into one entry, so the
# generated file has one `- catalog:` per catalog rather than duplicates
# (oc-mirror treats repeated catalog keys as separate, redundant mirrors).
catalogs = {}   # catalog ref -> list of (profile, package lines)
order = []
for prof, lines in operators:
    cat, pkgs, in_pkgs = None, [], False
    for ln in lines:
        m = re.match(r'\s*-\s*catalog:\s*(\S+)', ln)
        if m:
            if cat:
                catalogs.setdefault(cat, []).append((prof, pkgs))
            cat, pkgs, in_pkgs = m.group(1), [], False
            if cat not in order:
                order.append(cat)
            continue
        if re.match(r'\s*packages:\s*$', ln):
            in_pkgs = True
            continue
        if in_pkgs:
            pkgs.append(ln)
    if cat:
        catalogs.setdefault(cat, []).append((prof, pkgs))
        if cat not in order:
            order.append(cat)

def nonblank(lines):
    return [l for l in lines if l.strip()]

w = []
w.append(f"# Generated by scripts/12-compose-imageset.sh")
w.append(f"# {datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}")
w.append(f"# Profiles: base-platform {profile_list}")
w.append("#")
w.append("# Safe to edit by hand. Re-running the composer overwrites this file,")
w.append("# so persist lasting changes in imageset-configs/ instead.")
w.append("")
w.extend(l for l in header if l.strip() or True)
w.append("")
w.append("mirror:")
w.append("  platform:")
w.extend(platform)

if order:
    w.append("")
    w.append("  operators:")
    for cat in order:
        w.append(f"    - catalog: {cat}")
        w.append("      packages:")
        for prof, pkgs in catalogs[cat]:
            w.append(f"        # -- {prof}")
            w.extend(nonblank(pkgs))

if images:
    w.append("")
    w.append("  additionalImages:")
    for prof, lines in images:
        w.append(f"    # -- {prof}")
        w.extend(nonblank(lines))

text = "\n".join(w).rstrip() + "\n"

# Collapse runs of blank lines introduced by fragment spacing.
text = re.sub(r'\n{3,}', '\n\n', text)

for k in ("OCP_CHANNEL", "OCP_VERSION", "OCP_ARCH", "OCP_MINOR"):
    text = text.replace("${%s}" % k, os.environ[k])

leftover = set(re.findall(r'\$\{(\w+)\}', text))
if leftover:
    sys.stderr.write(f"[WARN]  Unsubstituted variables remain: {', '.join(sorted(leftover))}\n")

open(out_path, "w").write(text)
PY

ok "Wrote ${IMAGESET_CONFIG}"

# Validate the result parses as YAML if a parser happens to be available.
if python3 -c 'import yaml' 2>/dev/null; then
  if python3 -c "import yaml,sys; yaml.safe_load(open('${IMAGESET_CONFIG}'))" 2>/dev/null; then
    ok "Generated file parses as valid YAML"
  else
    die "Generated file is not valid YAML. Inspect ${IMAGESET_CONFIG}."
  fi
else
  info "PyYAML not installed -- skipping syntax validation (scripts/15-dry-run.sh will catch errors)"
fi

echo >&2
cat >&2 <<EOF
Read it before you mirror it:
    \${EDITOR:-vi} ${IMAGESET_CONFIG}

Then, in order:
    ./scripts/15-dry-run.sh         # minutes -- do all package names resolve?
    ./scripts/20-mirror-to-disk.sh  # hours
EOF
